title: DIGITAL.DZ
description: L'actualité tech et télécoms en Algérie
url: "https://bastaps.github.io"
baseurl: "/Basta-InfosTech"

# Paramètres de construction
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
include: [presse, img]
exclude: [README.md, Gemfile, Gemfile.lock]

# Encodage
encoding: "utf-8"
