title: DIGITAL.DZ
baseurl: "/Basta-InfosTech"
url: "https://bastaps.github.io"

# Configuration technique
markdown: kramdown
include: [presse, img]
future: true # Permet d'afficher les articles datés de 2026
encoding: "utf-8"
