# Configuration propre pour DIGITAL.DZ
_collections:
  posts:
    path: _posts
    output: true
    name: Mes Articles
    icon: article
    # On définit ici que tous les nouveaux articles utilisent le style "article"
    _defaults:
      layout: article

# Voici les cases que vous verrez à gauche
_inputs:
  title:
    type: text
    label: Titre de l'article
  date:
    type: date
    label: Date de publication
  lang:
    type: select
    label: Langue
    options:
      values: [ar, fr]
  category:
    type: text
    label: Catégorie
  description:
    type: textarea
    label: Résumé (Description)
  image:
    type: image
    label: Photo de couverture